version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/tmp
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  web:
    env_file: 
      - production.env
    build: .
    command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done; python manage.py makemigrations; python manage.py makemigrations core; python manage.py migrate; while :; do python manage.py runserver --noreload 0.0.0.0:8000; sleep 1; done"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: