version: '3'

services:
  db:
    env_file:
      - development.env
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/tmp
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  web:
    env_file: 
      - development.env
    build: .
    command: python manage.py runserver --noreload 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: